#!/usr/bin/python

import sys, os, glob, os.path, shutil, re
from optparse import OptionParser

glob = glob.glob

def cmd(c):
    if os.system(c) != 0:
        raise Exception('command execution failed: ' + c)

parser = OptionParser(usage = 'usage: %prog [-v VERSION][-l LINUX]')
parser.add_option('-v', action = 'store', type = 'string', dest = 'version', \
                  help = 'kvm-kmod release version', default = 'kvm-devel')
parser.add_option('-l', action = 'store', type = 'string', dest = 'linux', \
                  help = 'Linux kernel tree to sync from', \
                  default = 'linux')
parser.set_defaults()
(options, args) = parser.parse_args()
version = options.version
linux = options.linux

_re_cache = {}

def re_cache(regexp):
    global _re_cache
    if regexp not in _re_cache:
        _re_cache[regexp] = re.compile(regexp)
    return _re_cache[regexp]

def hack_content(fname, data):
    compat_apis = str.split(
        ''
        )
    result = []
    pr_fmt = ''
    inside_block_state = {}
    finish_endif = False

    def sub(regexp, repl, str):
        return re_cache(regexp).sub(repl, str)

    for line in data.splitlines():
        def match(regexp):
            return re_cache(regexp).search(line)

        def get_block_key(start_regexp, end_regexp):
            key = start_regexp + '\n' + end_regexp
            if not inside_block_state.has_key(key):
                inside_block_state[key] = False
            return key

        def inside_block(start_regexp, end_regexp):
            key = get_block_key(start_regexp, end_regexp)
            if inside_block_state[key]:
                if match(end_regexp):
                    inside_block_state[key] = False
            elif match(start_regexp):
                inside_block_state[key] = True
                return False
            return inside_block_state[key]

        def match_block_end(start_regexp, end_regexp):
            key = get_block_key(start_regexp, end_regexp)
            if inside_block_state[key]:
                if match(end_regexp):
                    inside_block_state[key] = False
                    return True
            elif match(start_regexp):
                inside_block_state[key] = True
            return False

        def w(line, result = result):
            result.append(line)

        orig = line
        f = line.split()
        if match(r'^#define pr_fmt'):
            pr_fmt = sub(r'#define pr_fmt\([^)]*\) ("[^"]*").*', r'\1', line) + ' '
            line = ''
        line = sub(r'pr_debug\(([^),]*)', r'pr_debug(' + pr_fmt + r'\1', line)
        if match(r'MODULE_AUTHOR'):
            w('MODULE_INFO(version, "%s");' % (version,))
        if fname == 'kvm_main.c' and inside_block(r'^int kvm_init\(', r'^}'):
            if match(r'return 0;'):
                w('\tprintk("loaded kvm module (%s)\\n");\n' % (version,))
        for ident in compat_apis:
            line = sub(r'\b' + ident + r'\b', 'kvm_' + ident, line)

        w(line)

    data = str.join('', [line + '\n' for line in result])
    return data

def hack_file(T, fname):
    fullname = T + '/' + fname
    data = file(fullname).read()
    data = hack_content(fname, data)
    file(fullname, 'w').write(data)

def unifdef(fname):
    data = file('unifdef.h').read() + file(fname).read()
    file(fname, 'w').write(data)

hack_files = {
    'x86': str.split('kvm_main.c mmu.c vmx.c svm.c x86.c x86.h irq.h lapic.c'
                     ' lapic.h i8254.c eventfd.c emulate.c async_pf.c'
                     ' cpuid.c pmu.c paging_tmpl.h'),
}

def mkdir(dir):
    if not os.path.exists(dir):
        os.makedirs(dir)

def cp(src, dst):
    mkdir(os.path.dirname(dst))
    file(dst, 'w').write(file(src).read())

def copy_if_changed(src, dst):
    for dir, subdirs, files in os.walk(src):
        ndir = dst + '/' + dir[len(src)+1:]
        mkdir(ndir)
        for fname in files:
            old = ndir + '/' + fname
            new = dir + '/' + fname
            try:
                if file(old).read() !=  file(new).read():
                    raise Exception('different.')
            except:
                cp(new, old)

def rmtree(path):
    if os.path.exists(path):
        shutil.rmtree(path)

def header_sync(arch):
    T = 'header'
    rmtree(T)
    for file in (glob('%(linux)s/include/linux/kvm*.h' % { 'linux': linux }) +
                 glob('%(linux)s/include/linux/vfio.h' % { 'linux': linux }) +
                 glob('%(linux)s/include/uapi/linux/kvm*.h' % { 'linux': linux })):
        out = ('%(T)s/include/linux/%(name)s'
               % { 'T': T, 'name': os.path.basename(file) })
        cp(file, out)
        unifdef(out)
    for file in (glob('%(linux)s/include/kvm/*.h' % { 'linux': linux })):
        out = ('%(T)s/include/kvm/%(name)s'
               % { 'T': T, 'name': os.path.basename(file) })
        cp(file, out)
        unifdef(out)
    for file in glob(('%(linux)s/include/trace/events/kvm*.h'
                      % { 'linux': linux })):
        out = ('%(T)s/include/trace/events/%(name)s'
               % { 'T': T, 'name': os.path.basename(file) })
        cp(file, out)
        unifdef(out)
    arch_headers = (
        [x
         for dir in ['%(linux)s/arch/%(arch)s/include/asm/kvm*.h',
                     '%(linux)s/arch/%(arch)s/include/asm/vmx.h',
                     '%(linux)s/arch/%(arch)s/include/asm/svm.h',
                     '%(linux)s/arch/%(arch)s/include/asm/virtext*.h']
         for x in glob(dir % { 'arch': arch, 'linux': linux })
         ])
    for file in arch_headers:
        out = ('%(T)s/include/asm-%(arch)s/%(name)s'
               % { 'T': T, 'name': os.path.basename(file), 'arch': arch })
        cp(file, out)
        unifdef(out)
    arch_uapi_headers = (
        [x
         for dir in ['%(linux)s/arch/%(arch)s/include/uapi/asm/kvm*.h',
                     '%(linux)s/arch/%(arch)s/include/uapi/asm/vmx.h',
                     '%(linux)s/arch/%(arch)s/include/uapi/asm/svm.h',
                     '%(linux)s/arch/%(arch)s/include/uapi/asm/msr-index.h',
                     '%(linux)s/arch/%(arch)s/include/uapi/asm/hyperv.h']
         for x in glob(dir % { 'arch': arch, 'linux': linux })
         ])
    for file in arch_uapi_headers:
        out = ('%(T)s/include/uapi/asm-%(arch)s/%(name)s'
               % { 'T': T, 'name': os.path.basename(file), 'arch': arch })
        cp(file, out)
        unifdef(out)
    hack_file(T, 'include/linux/kvm_host.h')
    hack_file(T, 'include/asm-%(arch)s/kvm_host.h' % { 'arch': arch })
    if arch == 'x86':
        hack_file(T, 'include/asm-x86/kvm_emulate.h')
    copy_if_changed(T, '.')
    rmtree(T)

def source_sync(arch):
    T = 'source'
    rmtree(T)
    sources = [file
               for pattern in ['%(linux)s/arch/%(arch)s/kvm/*.[cSh]',
                               '%(linux)s/virt/kvm/*.[cSh]']
               for file in glob(pattern % { 'linux': linux, 'arch': arch })
               if not file.endswith('.mod.c')
               ]
    for file in sources:
        out = ('%(T)s/%(name)s'
               % { 'T': T, 'name': os.path.basename(file) })
        cp(file, out)

    for i in glob(T + '/*.c'):
        unifdef(i)

    for i in hack_files[arch]:
        hack_file(T, i)

    copy_if_changed(T, arch)
    rmtree(T)

for arch in ['x86']:
    header_sync(arch)
    source_sync(arch)
